[package]
name = "vault"
version = "0.1.4"
edition = "2021"

[dependencies]
argon2 = "0.5.3"
chacha20poly1305 = "0.10.1"
rand = "0.9.2"
rpassword = "7.4.0"
zeroize = "1.8.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time = "0.3"
